// projectDSW/src/app/ranking/rankingsData.ts
export const rankings = {
  Páginas: {
    amigos: [
      { id: 'joao123', name: 'João', score: 43 },
      { id: 'maria456', name: 'Maria', score: 41 },
      { id: 'pedro789', name: 'Pedro', score: 40 },
      { id: 'ana012', name: 'Ana', score: 35 },
      { id: 'lucas345', name: 'Lucas', score: 31 },
      { id: 'carla678', name: 'Carla', score: 30 },
      { id: 'rafael910', name: 'Rafael', score: 27 },
      { id: 'bianca112', name: 'Bianca', score: 25 },
      { id: 'gustavo234', name: 'Gustavo', score: 22 },
      { id: 'camila567', name: 'Camila', score: 15 },
      {id: 'verbix', name: 'verbix', score: 30},
    ],
    geral: [
      { id: 'carlos111', name: 'Carlos', score: 195 },
      { id: 'fernanda222', name: 'Fernanda', score: 190 },
      { id: 'lucas345', name: 'Lucas', score: 185 },
      { id: 'juliana456', name: 'Juliana', score: 180 },
      { id: 'ricardo567', name: 'Ricardo', score: 175 },
      { id: 'tatiana678', name: 'Tatiana', score: 170 },
      { id: 'eduardo789', name: 'Eduardo', score: 165 },
      { id: 'vanessa890', name: 'Vanessa', score: 160 },
      { id: 'marcos901', name: 'Marcos', score: 155 },
      { id: 'patricia123', name: 'Patrícia', score: 150 },
      { id: 'renato234', name: 'Renato', score: 145 },
      { id: 'larissa345', name: 'Larissa', score: 140 },
      { id: 'miguel456', name: 'Miguel', score: 135 },
      { id: 'alice567', name: 'Alice', score: 130 },
      { id: 'heitor678', name: 'Heitor', score: 125 },
      { id: 'laura789', name: 'Laura', score: 120 },
      { id: 'davi890', name: 'Davi', score: 115 },
      { id: 'manuela901', name: 'Manuela', score: 110 },
      { id: 'arthur012', name: 'Arthur', score: 105 },
      { id: 'valentina123', name: 'Valentina', score: 100 },
      { id: 'gabriel234', name: 'Gabriel', score: 95 },
      { id: 'sophia345', name: 'Sophia', score: 90 },
      { id: 'bernardo456', name: 'Bernardo', score: 85 },
      { id: 'helena567', name: 'Helena', score: 80 },
      { id: 'matheus678', name: 'Matheus', score: 75 },
      { id: 'luiza789', name: 'Luiza', score: 70 },
      { id: 'rafael910', name: 'Rafael', score: 65 },
      { id: 'julia123', name: 'Júlia', score: 60 },
      { id: 'felipe234', name: 'Felipe', score: 55 },
      { id: 'lorena345', name: 'Lorena', score: 50 },
      { id: 'guilherme456', name: 'Guilherme', score: 45 },
      {id: 'verbix', name: 'verbix', score: 30}
    ],
  },
  Livros: {
    amigos: [
      { id: 'felipe234', name: 'Felipe', score: 38 },
      { id: 'sofia567', name: 'Sofia', score: 36 },
      { id: 'bruno678', name: 'Bruno', score: 34 },
      { id: 'isabela789', name: 'Isabela', score: 29 },
      { id: 'leonardo890', name: 'Leonardo', score: 27 },
      { id: 'gabriela901', name: 'Gabriela', score: 25 },
      { id: 'thiago012', name: 'Thiago', score: 24 },
      { id: 'mariana123', name: 'Mariana', score: 22 },
      { id: 'andre234', name: 'André', score: 19 },
      { id: 'juliana345', name: 'Juliana', score: 17 },
      {id: 'verbix', name: 'verbix', score: 5},
    ],
    geral: [
      { id: 'rodrigo111', name: 'Rodrigo', score: 195 },
      { id: 'paula222', name: 'Paula', score: 190 },
      { id: 'carlos333', name: 'Carlos', score: 185 },
      { id: 'fernanda444', name: 'Fernanda', score: 180 },
      { id: 'ricardo555', name: 'Ricardo', score: 175 },
      { id: 'tatiana666', name: 'Tatiana', score: 170 },
      { id: 'eduardo777', name: 'Eduardo', score: 165 },
      { id: 'vanessa888', name: 'Vanessa', score: 160 },
      { id: 'marcos999', name: 'Marcos', score: 155 },
      { id: 'patricia111', name: 'Patrícia', score: 150 },
      { id: 'renato222', name: 'Renato', score: 145 },
      { id: 'larissa333', name: 'Larissa', score: 140 },
      { id: 'miguel444', name: 'Miguel', score: 135 },
      { id: 'alice555', name: 'Alice', score: 130 },
      { id: 'heitor666', name: 'Heitor', score: 125 },
      { id: 'laura777', name: 'Laura', score: 120 },
      { id: 'davi888', name: 'Davi', score: 115 },
      { id: 'manuela999', name: 'Manuela', score: 110 },
      { id: 'arthur012', name: 'Arthur', score: 105 },
      { id: 'valentina123', name: 'Valentina', score: 100 },
      { id: 'gabriel234', name: 'Gabriel', score: 95 },
      { id: 'sophia345', name: 'Sophia', score: 90 },
      { id: 'bernardo456', name: 'Bernardo', score: 85 },
      { id: 'helena567', name: 'Helena', score: 80 },
      { id: 'matheus678', name: 'Matheus', score: 75 },
      { id: 'luiza789', name: 'Luiza', score: 70 },
      { id: 'rafael890', name: 'Rafael', score: 65 },
      { id: 'julia901', name: 'Júlia', score: 60 },
      { id: 'felipe234', name: 'Felipe', score: 55 },
      { id: 'lorena345', name: 'Lorena', score: 50 },
      {id: 'verbix', name: 'verbix', score: 5},
    ],
  },
  Sequências: {
    amigos: [
      { id: 'claudia101', name: 'Cláudia', score: 28 },
      { id: 'beatriz202', name: 'Beatriz', score: 27 },
      { id: 'ricardo303', name: 'Ricardo', score: 25 },
      { id: 'michele404', name: 'Michele', score: 22 },
      { id: 'vitor505', name: 'Vitor', score: 21 },
      { id: 'amanda606', name: 'Amanda', score: 18 },
      { id: 'pedro707', name: 'Pedro', score: 15 },
      { id: 'marcio808', name: 'Márcio', score: 12 },
      { id: 'andre909', name: 'André', score: 10 },
      { id: 'livia010', name: 'Lívia', score: 9 },
      {id: 'verbix', name: 'verbix', score: 3},
    ],
    geral: [
      { id: 'carlos111', name: 'Carlos', score: 185 },
      { id: 'lucas345', name: 'Lucas', score: 180 },
      { id: 'renato567', name: 'Renato', score: 175 },
      { id: 'patricia678', name: 'Patrícia', score: 170 },
      { id: 'tatiana789', name: 'Tatiana', score: 165 },
      { id: 'eduardo890', name: 'Eduardo', score: 160 },
      { id: 'marcos012', name: 'Marcos', score: 155 },
      { id: 'vanessa123', name: 'Vanessa', score: 150 },
      { id: 'heitor234', name: 'Heitor', score: 145 },
      { id: 'gabriel345', name: 'Gabriel', score: 140 },
      { id: 'sophia456', name: 'Sophia', score: 135 },
      { id: 'bernardo567', name: 'Bernardo', score: 130 },
      { id: 'alice678', name: 'Alice', score: 125 },
      { id: 'matheus789', name: 'Matheus', score: 120 },
      { id: 'luiza890', name: 'Luiza', score: 115 },
      { id: 'rafael901', name: 'Rafael', score: 110 },
      { id: 'felipe012', name: 'Felipe', score: 105 },
      { id: 'lorena123', name: 'Lorena', score: 100 },
      {id: 'verbix', name: 'verbix', score: 3},
    ],
  },
  Missões: {
    amigos: [
      { id: 'aline101', name: 'Aline', score: 28 },
      { id: 'luana202', name: 'Luana', score: 26 },
      { id: 'david303', name: 'David', score: 24 },
      { id: 'guilherme404', name: 'Guilherme', score: 22 },
      { id: 'raquel505', name: 'Raquel', score: 20 },
      { id: 'renato606', name: 'Renato', score: 18 },
      { id: 'claudio707', name: 'Cláudio', score: 15 },
      { id: 'mario808', name: 'Mário', score: 13 },
      { id: 'carla909', name: 'Carla', score: 11 },
      { id: 'vanessa010', name: 'Vanessa', score: 9 },
      {id: 'verbix', name: 'verbix', score: 30},
    ],
    geral: [
      { id: 'joao123', name: 'João', score: 195 },
      { id: 'lucas345', name: 'Lucas', score: 190 },
      { id: 'pedro789', name: 'Pedro', score: 185 },
      { id: 'maria456', name: 'Maria', score: 180 },
      { id: 'rafael910', name: 'Rafael', score: 175 },
      { id: 'carla678', name: 'Carla', score: 170 },
      { id: 'gustavo234', name: 'Gustavo', score: 165 },
      { id: 'bianca112', name: 'Bianca', score: 160 },
      { id: 'camila567', name: 'Camila', score: 155 },
      { id: 'gustavo123', name: 'Gustavo', score: 150 },
      {id: 'verbix', name: 'verbix', score: 30},
    ],
  },
};
