// projectDSW/src/app/ranking/rankingsData.ts
export const rankings = {
  Páginas: {
    amigos: [
      { name: 'João', score: 43 },
      { name: 'Maria', score: 41 },
      { name: 'Pedro', score: 40 },
      { name: 'Ana', score: 35 },
      { name: 'Lucas', score: 31 },
      { name: 'Carla', score: 30 },
      { name: 'Rafael', score: 27 },
      { name: 'Bianca', score: 25 },
      { name: 'Gustavo', score: 22 },
      { name: 'Camila', score: 15 },
    ],
    geral: [
      { name: 'Carlos', score: 195 },
      { name: 'Fernanda', score: 190 },
      { name: 'Lucas', score: 185 },
      { name: 'Juliana', score: 180 },
      { name: 'Ricardo', score: 175 },
      { name: 'Tatiana', score: 170 },
      { name: 'Eduardo', score: 165 },
      { name: 'Vanessa', score: 160 },
      { name: 'Marcos', score: 155 },
      { name: 'Patrícia', score: 150 },
      { name: 'Renato', score: 145 },
      { name: 'Larissa', score: 140 },
      { name: 'Miguel', score: 135 },
      { name: 'Alice', score: 130 },
      { name: 'Heitor', score: 125 },
      { name: 'Laura', score: 120 },
      { name: 'Davi', score: 115 },
      { name: 'Manuela', score: 110 },
      { name: 'Arthur', score: 105 },
      { name: 'Valentina', score: 100 },
      { name: 'Gabriel', score: 95 },
      { name: 'Sophia', score: 90 },
      { name: 'Bernardo', score: 85 },
      { name: 'Helena', score: 80 },
      { name: 'Matheus', score: 75 },
      { name: 'Luiza', score: 70 },
      { name: 'Rafael', score: 65 },
      { name: 'Júlia', score: 60 },
      { name: 'Felipe', score: 55 },
      { name: 'Lorena', score: 50 },
      { name: 'Guilherme', score: 45 },
      { name: 'Lívia', score: 40 },
      { name: 'Enzo', score: 35 },
      { name: 'Giovanna', score: 30 },
      { name: 'Nicolas', score: 25 },
      { name: 'Maria Eduarda', score: 20 },
      { name: 'Lorenzo', score: 15 },
      { name: 'Beatriz', score: 10 },
      { name: 'Gustavo', score: 5 },
      // Adicione mais nomes e pontuações aqui até completar 100
    ],
  },
  Livros: {
    amigos: [
      { name: 'Felipe', score: 38 },
      { name: 'Sofia', score: 36 },
      { name: 'Bruno', score: 34 },
      { name: 'Isabela', score: 29 },
      { name: 'Leonardo', score: 27 },
      { name: 'Gabriela', score: 25 },
      { name: 'Thiago', score: 24 },
      { name: 'Mariana', score: 22 },
      { name: 'André', score: 19 },
      { name: 'Juliana', score: 17 },
    ],
    geral: [
      { name: 'Rodrigo', score: 195 },
      { name: 'Paula', score: 190 },
      { name: 'Carlos', score: 185 },
      { name: 'Fernanda', score: 180 },
      { name: 'Ricardo', score: 175 },
      { name: 'Tatiana', score: 170 },
      { name: 'Eduardo', score: 165 },
      { name: 'Vanessa', score: 160 },
      { name: 'Marcos', score: 155 },
      { name: 'Patrícia', score: 150 },
      { name: 'Renato', score: 145 },
      { name: 'Larissa', score: 140 },
      { name: 'Miguel', score: 135 },
      { name: 'Alice', score: 130 },
      { name: 'Heitor', score: 125 },
      { name: 'Laura', score: 120 },
      { name: 'Davi', score: 115 },
      { name: 'Manuela', score: 110 },
      { name: 'Arthur', score: 105 },
      { name: 'Valentina', score: 100 },
      { name: 'Gabriel', score: 95 },
      { name: 'Sophia', score: 90 },
      { name: 'Bernardo', score: 85 },
      { name: 'Helena', score: 80 },
      { name: 'Matheus', score: 75 },
      { name: 'Luiza', score: 70 },
      { name: 'Rafael', score: 65 },
      { name: 'Júlia', score: 60 },
      { name: 'Felipe', score: 55 },
      { name: 'Lorena', score: 50 },
      { name: 'Guilherme', score: 45 },
      { name: 'Lívia', score: 40 },
      { name: 'Enzo', score: 35 },
      { name: 'Giovanna', score: 30 },
      { name: 'Nicolas', score: 25 },
      { name: 'Maria Eduarda', score: 20 },
      { name: 'Lorenzo', score: 15 },
      { name: 'Beatriz', score: 10 },
      { name: 'Gustavo', score: 5 },
      // Adicione mais nomes e pontuações aqui até completar 100
    ],
  },
  Sequências: {
    amigos: [
      { name: 'Leonardo', score: 35 },
      { name: 'Gabriela', score: 33 },
      { name: 'Thiago', score: 27 },
      { name: 'Mariana', score: 26 },
      { name: 'André', score: 22 },
      { name: 'Juliana', score: 19 },
      { name: 'Rodrigo', score: 15 },
      { name: 'Paula', score: 12 },
      { name: 'Carlos', score: 9 },
      { name: 'Fernanda', score: 7 },
    ],
    geral: [
      { name: 'Ricardo', score: 195 },
      { name: 'Tatiana', score: 190 },
      { name: 'Eduardo', score: 185 },
      { name: 'Vanessa', score: 180 },
      { name: 'Marcos', score: 175 },
      { name: 'Patrícia', score: 170 },
      { name: 'Renato', score: 165 },
      { name: 'Larissa', score: 160 },
      { name: 'Miguel', score: 155 },
      { name: 'Alice', score: 150 },
      { name: 'Heitor', score: 145 },
      { name: 'Laura', score: 140 },
      { name: 'Davi', score: 135 },
      { name: 'Manuela', score: 130 },
      { name: 'Arthur', score: 125 },
      { name: 'Valentina', score: 120 },
      { name: 'Gabriel', score: 115 },
      { name: 'Sophia', score: 110 },
      { name: 'Bernardo', score: 105 },
      { name: 'Helena', score: 100 },
      { name: 'Matheus', score: 95 },
      { name: 'Luiza', score: 90 },
      { name: 'Rafael', score: 85 },
      { name: 'Júlia', score: 80 },
      { name: 'Felipe', score: 75 },
      { name: 'Lorena', score: 70 },
      { name: 'Guilherme', score: 65 },
      { name: 'Lívia', score: 60 },
      { name: 'Enzo', score: 55 },
      { name: 'Giovanna', score: 50 },
      { name: 'Nicolas', score: 45 },
      { name: 'Maria Eduarda', score: 40 },
      { name: 'Lorenzo', score: 35 },
      { name: 'Beatriz', score: 30 },
      { name: 'Gustavo', score: 25 },
      { name: 'Samuel', score: 20 },
      { name: 'Cecília', score: 15 },
      { name: 'João Pedro', score: 10 },
      { name: 'Eloá', score: 5 },
      // Adicione mais nomes e pontuações aqui até completar 100
    ],
  },
  Missões: {
    amigos: [
      { name: 'Rodrigo', score: 33 },
      { name: 'Paula', score: 29 },
      { name: 'Carlos', score: 26 },
      { name: 'Fernanda', score: 25 },
      { name: 'Ricardo', score: 23 },
      { name: 'Tatiana', score: 22 },
      { name: 'Eduardo', score: 20 },
      { name: 'Vanessa', score: 18 },
      { name: 'Marcos', score: 14 },
      { name: 'Patrícia', score: 11 },
    ],
    geral: [
      { name: 'Renato', score: 195 },
      { name: 'Larissa', score: 190 },
      { name: 'Carlos', score: 185 },
      { name: 'Fernanda', score: 180 },
      { name: 'Lucas', score: 175 },
      { name: 'Juliana', score: 170 },
      { name: 'Ricardo', score: 165 },
      { name: 'Tatiana', score: 160 },
      { name: 'Eduardo', score: 155 },
      { name: 'Vanessa', score: 150 },
      { name: 'Miguel', score: 145 },
      { name: 'Alice', score: 140 },
      { name: 'Heitor', score: 135 },
      { name: 'Laura', score: 130 },
      { name: 'Davi', score: 125 },
      { name: 'Manuela', score: 120 },
      { name: 'Arthur', score: 115 },
      { name: 'Valentina', score: 110 },
      { name: 'Gabriel', score: 105 },
      { name: 'Sophia', score: 100 },
      { name: 'Bernardo', score: 95 },
      { name: 'Helena', score: 90 },
      { name: 'Matheus', score: 85 },
      { name: 'Luiza', score: 80 },
      { name: 'Rafael', score: 75 },
      { name: 'Júlia', score: 70 },
      { name: 'Felipe', score: 65 },
      { name: 'Lorena', score: 60 },
      { name: 'Guilherme', score: 55 },
      { name: 'Lívia', score: 50 },
      { name: 'Enzo', score: 45 },
      { name: 'Giovanna', score: 40 },
      { name: 'Nicolas', score: 35 },
      { name: 'Maria Eduarda', score: 30 },
      { name: 'Lorenzo', score: 25 },
      { name: 'Beatriz', score: 20 },
      { name: 'Gustavo', score: 15 },
      { name: 'Samuel', score: 10 },
      { name: 'Cecília', score: 5 },
      // Adicione mais nomes e pontuações aqui até completar 100
    ],
  },
};