export const rankings = {
  Páginas: {
    amigos: [
      { id: 'joao123', name: 'João', score: 43, avatar: 'Diogo' },
      { id: 'maria456', name: 'Maria', score: 41, avatar: 'Erica' },
      { id: 'pedro789', name: 'Pedro', score: 40, avatar: 'Pablo' },
      { id: 'ana012', name: 'Ana', score: 35, avatar: 'Safira' },
      { id: 'lucas345', name: 'Lucas', score: 31, avatar: 'Henry' },
      { id: 'carla678', name: 'Carla', score: 30, avatar: 'Tempest' },
      { id: 'rafael910', name: 'Rafael', score: 27, avatar: 'Pietro' },
      { id: 'bianca112', name: 'Bianca', score: 25, avatar: 'Margo' },
      { id: 'gustavo234', name: 'Gustavo', score: 22, avatar: 'Gasby' },
      { id: 'camila567', name: 'Camila', score: 15, avatar: 'Safira' },
      { id: 'verbix', name: 'Verbix', score: 30, avatar: 'Diogo' },
    ],
    geral: [
      { id: 'carlos111', name: 'Carlos', score: 195, avatar: 'Diogo' },
      { id: 'fernanda222', name: 'Fernanda', score: 190, avatar: 'Safira' },
      { id: 'lucas345', name: 'Lucas', score: 185, avatar: 'Henry' },
      { id: 'juliana456', name: 'Juliana', score: 180, avatar: 'Erica' },
      { id: 'ricardo567', name: 'Ricardo', score: 175, avatar: 'Frederico' },
      { id: 'joao123', name: 'João', score: 43, avatar: 'Diogo' },
      { id: 'maria456', name: 'Maria', score: 41, avatar: 'Erica' },
      { id: 'pedro789', name: 'Pedro', score: 40, avatar: 'Pablo' },
      { id: 'ana012', name: 'Ana', score: 35, avatar: 'Safira' },
      { id: 'carla678', name: 'Carla', score: 30, avatar: 'Tempest' },
      { id: 'rafael910', name: 'Rafael', score: 27, avatar: 'Pietro' },
      { id: 'bianca112', name: 'Bianca', score: 25, avatar: 'Margo' },
      { id: 'gustavo234', name: 'Gustavo', score: 22, avatar: 'Gasby' },
      { id: 'camila567', name: 'Camila', score: 15, avatar: 'Safira' },
      { id: 'verbix', name: 'Verbix', score: 30, avatar: 'Diogo' },
    ],
  },
  Livros: {
    amigos: [
      { id: 'felipe234', name: 'Felipe', score: 38, avatar: 'Frederico' },
      { id: 'sofia567', name: 'Sofia', score: 36, avatar: 'Erica' },
      { id: 'bruno678', name: 'Bruno', score: 34, avatar: 'Diogo' },
      { id: 'isabela789', name: 'Isabela', score: 29, avatar: 'Safira' },
      { id: 'leonardo890', name: 'Leonardo', score: 27, avatar: 'Pietro' },
      { id: 'gabriela901', name: 'Gabriela', score: 25, avatar: 'Margo' },
      { id: 'thiago012', name: 'Thiago', score: 24, avatar: 'Gasby' },
      { id: 'mariana123', name: 'Mariana', score: 22, avatar: 'Tempest' },
      { id: 'andre234', name: 'André', score: 19, avatar: 'Pablo' },
      { id: 'juliana345', name: 'Juliana', score: 17, avatar: 'Safira' },
      { id: 'verbix', name: 'Verbix', score: 5, avatar: 'Diogo' },
    ],
    geral: [
      { id: 'rodrigo111', name: 'Rodrigo', score: 195, avatar: 'Diogo' },
      { id: 'paula222', name: 'Paula', score: 190, avatar: 'Erica' },
      { id: 'carlos333', name: 'Carlos', score: 185, avatar: 'Pietro' },
      { id: 'fernanda444', name: 'Fernanda', score: 180, avatar: 'Margo' },
      { id: 'ricardo555', name: 'Ricardo', score: 175, avatar: 'Frederico' },
      { id: 'felipe234', name: 'Felipe', score: 38, avatar: 'Frederico' },
      { id: 'sofia567', name: 'Sofia', score: 36, avatar: 'Erica' },
      { id: 'bruno678', name: 'Bruno', score: 34, avatar: 'Diogo' },
      { id: 'isabela789', name: 'Isabela', score: 29, avatar: 'Safira' },
      { id: 'leonardo890', name: 'Leonardo', score: 27, avatar: 'Pietro' },
      { id: 'gabriela901', name: 'Gabriela', score: 25, avatar: 'Margo' },
      { id: 'thiago012', name: 'Thiago', score: 24, avatar: 'Gasby' },
      { id: 'mariana123', name: 'Mariana', score: 22, avatar: 'Tempest' },
      { id: 'andre234', name: 'André', score: 19, avatar: 'Pablo' },
      { id: 'juliana345', name: 'Juliana', score: 17, avatar: 'Safira' },
      { id: 'verbix', name: 'Verbix', score: 5, avatar: 'Diogo' },
    ],
  },
  Sequências: {
    amigos: [
      { id: 'joao234', name: 'João', score: 20, avatar: 'Diogo' },
      { id: 'maria567', name: 'Maria', score: 18, avatar: 'Erica' },
      { id: 'pedro890', name: 'Pedro', score: 15, avatar: 'Pablo' },
      { id: 'ana123', name: 'Ana', score: 12, avatar: 'Safira' },
      { id: 'rafael345', name: 'Rafael', score: 10, avatar: 'Gasby' },
      { id: 'carla678', name: 'Carla', score: 8, avatar: 'Tempest' },
      { id: 'gustavo910', name: 'Gustavo', score: 6, avatar: 'Frederico' },
      { id: 'lucas111', name: 'Lucas', score: 4, avatar: 'Henry' },
      { id: 'verbix', name: 'Verbix', score: 3, avatar: 'Diogo' },
    ],
    geral: [
      { id: 'rodrigo567', name: 'Rodrigo', score: 60, avatar: 'Frederico' },
      { id: 'paula678', name: 'Paula', score: 55, avatar: 'Erica' },
      { id: 'carlos890', name: 'Carlos', score: 50, avatar: 'Diogo' },
      { id: 'fernanda901', name: 'Fernanda', score: 45, avatar: 'Safira' },
      { id: 'ricardo012', name: 'Ricardo', score: 40, avatar: 'Gasby' },
      { id: 'joao234', name: 'João', score: 20, avatar: 'Diogo' },
      { id: 'maria567', name: 'Maria', score: 18, avatar: 'Erica' },
      { id: 'pedro890', name: 'Pedro', score: 15, avatar: 'Pablo' },
      { id: 'ana123', name: 'Ana', score: 12, avatar: 'Safira' },
      { id: 'rafael345', name: 'Rafael', score: 10, avatar: 'Gasby' },
      { id: 'carla678', name: 'Carla', score: 8, avatar: 'Tempest' },
      { id: 'gustavo910', name: 'Gustavo', score: 6, avatar: 'Frederico' },
      { id: 'lucas111', name: 'Lucas', score: 4, avatar: 'Henry' },
      { id: 'verbix', name: 'Verbix', score: 3, avatar: 'Diogo' },
    ],
  },
  Missões: {
    amigos: [
      { id: 'felipe567', name: 'Felipe', score: 80, avatar: 'Frederico' },
      { id: 'sofia678', name: 'Sofia', score: 78, avatar: 'Erica' },
      { id: 'bruno789', name: 'Bruno', score: 75, avatar: 'Diogo' },
      { id: 'isabela890', name: 'Isabela', score: 70, avatar: 'Safira' },
      { id: 'leonardo901', name: 'Leonardo', score: 65, avatar: 'Pietro' },
      { id: 'gabriela012', name: 'Gabriela', score: 60, avatar: 'Margo' },
      { id: 'thiago123', name: 'Thiago', score: 55, avatar: 'Gasby' },
      { id: 'mariana234', name: 'Mariana', score: 50, avatar: 'Tempest' },
      { id: 'andre345', name: 'André', score: 45, avatar: 'Pablo' },
      { id: 'verbix', name: 'Verbix', score: 10, avatar: 'Diogo' },
    ],
    geral: [
      { id: 'rodrigo890', name: 'Rodrigo', score: 200, avatar: 'Diogo' },
      { id: 'paula901', name: 'Paula', score: 190, avatar: 'Safira' },
      { id: 'carlos012', name: 'Carlos', score: 185, avatar: 'Henry' },
      { id: 'fernanda123', name: 'Fernanda', score: 180, avatar: 'Erica' },
      { id: 'ricardo234', name: 'Ricardo', score: 175, avatar: 'Frederico' },
      { id: 'felipe567', name: 'Felipe', score: 80, avatar: 'Frederico' },
      { id: 'sofia678', name: 'Sofia', score: 78, avatar: 'Erica' },
      { id: 'bruno789', name: 'Bruno', score: 75, avatar: 'Diogo' },
      { id: 'isabela890', name: 'Isabela', score: 70, avatar: 'Safira' },
      { id: 'leonardo901', name: 'Leonardo', score: 65, avatar: 'Pietro' },
      { id: 'gabriela012', name: 'Gabriela', score: 60, avatar: 'Margo' },
      { id: 'thiago123', name: 'Thiago', score: 55, avatar: 'Gasby' },
      { id: 'mariana234', name: 'Mariana', score: 50, avatar: 'Tempest' },
      { id: 'andre345', name: 'André', score: 45, avatar: 'Pablo' },
      { id: 'verbix', name: 'Verbix', score: 10, avatar: 'Diogo' },
    ],
  },
};
